# Generated by Django 6.0.3 on 2026-03-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_proposal_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
        migrations.AddField(
            model_name='proposal',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proposal',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='terms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proposal',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Enviada', 'Enviada'), ('Aprovada', 'Aprovada'), ('Recusada', 'Recusada'), ('Negociando', 'Negociando')], default='Rascunho', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
