# Generated by Django 6.0.3 on 2026-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price',
            new_name='price_monthly',
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='api_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='webhook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='Meta/WhatsApp Business API Phone Number ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='limits',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='modules',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instance',
            name='provider',
            field=models.CharField(default='evolution', max_length=100),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('CONNECTED', 'Conectado'), ('DISCONNECTED', 'Desconectado'), ('QRCODE', 'Aguardando QR Code'), ('PAIRING', 'Pareando')], default='DISCONNECTED', max_length=20),
        ),
    ]
