# Generated by Django 6.0.3 on 2026-03-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_master', '0002_rename_price_plan_price_monthly_company_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(default='active', help_text='active, past_due, canceled, trialing', max_length=50),
        ),
    ]
